version: '3.8'

services:
  gorizont_bot:
    build: .
    container_name: gorizont_bot
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./gorizont.db:/app/gorizont.db # Сохраняем базу SQLite
      - ./app_data:/app/app_data       # Сохраняем медиа/вложения
      - ./logs:/app/logs               # Логи
    # По желанию: Если добавите Redis:
    # depends_on:
    #   - redis

  # Если в будущем перейдете на Redis для FSM (раскомментировать)
  # redis:
  #   image: redis:alpine
  #   container_name: gorizont_redis
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data

# volumes:
#   redis_data:
