"""pilot_twins

Revision ID: 31d519fa89af
Revises: ea370f4f23b8
Create Date: 2026-03-31 03:45:45.112928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31d519fa89af'
down_revision: Union[str, None] = 'ea370f4f23b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pilot_twins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('total_flight_hours', sa.Float(), nullable=False),
    sa.Column('total_missions', sa.Integer(), nullable=False),
    sa.Column('safety_score', sa.Float(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('momoa_grade', sa.String(length=10), nullable=False),
    sa.Column('skills_json', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pilot_twins')
    # ### end Alembic commands ###
